function currentMonster(){return battle&&battle.monster?battle.monster:worlds[battle.world-1].m[battle.index]}
function skillButtons(){return `<button class="btn blue" onclick="chooseSkill('slash')">⚔️ 斬擊<br><small>免費</small></button><button class="btn red" onclick="chooseSkill('fire')">🔥 火焰斬<br><small>2 MP</small></button><button class="btn purple" onclick="chooseSkill('heavy')">💫 重擊<br><small>3 MP</small></button><button class="btn green" onclick="chooseSkill('heal')">💚 治癒術<br><small>3 MP</small></button><button class="btn gold" onclick="chooseSkill('thunder')">⚡ 雷電術<br><small>3 MP</small></button><button class="btn iceBtn" onclick="chooseSkill('ice')">❄️ 冰凍術<br><small>2 MP</small></button><button class="btn ultimateBtn" onclick="chooseSkill('ultimate')">💥 必殺技<br><small>Combo 5＋4 MP</small></button><button class="btn itemBtn" onclick="useBattleItem('potion')">🍎 HP藥 ×${st.items.potion}</button><button class="btn itemBtn" onclick="useBattleItem('ether')">🔷 MP藥 ×${st.items.ether}</button>`}
function useBattleItem(type){if(!battle||!battle.active)return;if((st.items[type]||0)<=0){toast('這個道具用完了！');return}if(type==='potion'){if(battle.hp>=hpMax()){toast('HP 已經是滿的');return}st.items.potion--;battle.hp=Math.min(hpMax(),battle.hp+5);toast('🍎 HP +5')}else{if(battle.mp>=mpMax()){toast('MP 已經是滿的');return}st.items.ether--;battle.mp=Math.min(mpMax(),battle.mp+4);toast('🔷 MP +4')}store();updateBattle();$('actions').innerHTML=skillButtons();renderHud()}
function answerQuestion(btn,i){document.querySelectorAll('.ans').forEach(x=>x.disabled=true);if(i===currentQ.a){btn.classList.add('good');st.stars++;st.combo++;st.quest.correct++;if(st.combo>=5)st.quest.combo5=1;store();setTimeout(()=>{$('qModal').classList.remove('show');resolveSkill(true)},450)}else{btn.classList.add('bad');st.combo=0;store();setTimeout(()=>{$('qModal').classList.remove('show');resolveSkill(false)},600)}}
function resolveSkill(ok){if(!ok){enemyAttack();return}const d=skillData[battle.skill];battle.mp-=d.cost;if(battle.skill==='heal'){battle.hp=Math.min(hpMax(),battle.hp+5);animate('heroChar','magic');updateBattle();$('actions').innerHTML=skillButtons();toast('💚 HP +5');return}let extra={slash:0,fire:2,heavy:4,thunder:3,ice:1,ultimate:7}[battle.skill]||0;if(battle.skill==='ice')battle.enemyWeaken=1;const bonus=1+Math.min(st.combo,5)*.12,base=attack()+extra,dmg=Math.round(base*bonus);animate('heroChar',battle.skill==='slash'?'attack':'magic');setTimeout(()=>{animate('monsterChar','hit');battle.mhp=Math.max(0,battle.mhp-dmg);updateBattle();if(battle.mhp<=0)winBattle();else{$('statusText').textContent=`${d.name}命中！造成 ${dmg} 傷害${battle.skill==='ice'?'，敵人下一擊減弱':''}。Combo ${st.combo}`;$('actions').innerHTML=skillButtons()}},170)}
function enemyAttack(){animate('monsterChar','enemyAttack');setTimeout(()=>{animate('heroChar','hit');const m=currentMonster();let raw=battle.rare?3:m[3]?4:battle.index===3?3:2;let dmg=Math.max(1,raw-defense()-(battle.enemyWeaken||0));battle.enemyWeaken=0;battle.hp=Math.max(0,battle.hp-dmg);battle.mp=Math.min(mpMax(),battle.mp+1);if(battle.hp===0){battle.hp=hpMax();battle.mp=mpMax();toast('勇者在檢查點復活！')}updateBattle();$('statusText').textContent=`答錯，受到 ${dmg} 傷害；MP +1。`;$('actions').innerHTML=skillButtons()},170)}
function updateBattle(){const m=currentMonster();$('heroHpText').textContent=`${battle.hp}/${hpMax()}`;$('heroHpBar').style.width=battle.hp/hpMax()*100+'%';$('heroMpText').textContent=`${battle.mp}/${mpMax()}`;$('heroMpBar').style.width=battle.mp/mpMax()*100+'%';$('monsterName').textContent=`${m[0]} ${m[1]}${battle.rare?' 🌟':''}`;$('monsterHpText').textContent=`${battle.mhp}/${m[2]}`;$('monsterHpBar').style.width=battle.mhp/m[2]*100+'%';$('monsterChar').textContent=m[0];$('monsterChar').classList.toggle('boss',!!m[3]||battle.rare);renderHud()}
function battleReward(i,boss){if(boss)return {coin:12,xp:8,label:'Boss'};if(i===3)return {coin:7,xp:5,label:'精英怪'};if(i===2)return {coin:5,xp:4,label:'進階怪'};return {coin:4,xp:3,label:'普通怪'}}
function winBattle(){battle.active=false;if(battle.rare)return winRareBattle();const w=worlds[battle.world-1],m=w.m[battle.index];st.defeated[w.id]=st.defeated[w.id]||[];if(!st.defeated[w.id].includes(battle.index))st.defeated[w.id].push(battle.index);const boss=!!m[3],r=battleReward(battle.index,boss);st.coins+=r.coin;st.xp+=r.xp;st.quest.wins++;if(boss)st.quest.boss++;store();toast(`🏆 擊倒 ${m[1]}！`);$('statusText').textContent=`勝利！${r.label} 掉落 ${r.coin} 金幣、${r.xp} XP。`;$('actions').innerHTML='<button class="btn green" onclick="continueAdventure()">探索下一區域 ➡️</button>';checkLevel();renderHud();renderInventory();renderQuests()}
function winRareBattle(){const m=currentMonster(),coin=12+st.world*2,xp=6;st.coins+=coin;st.xp+=xp;st.quest.wins++;let drop=null;if(Math.random()<.48){drop=randomGear();if(!st.lootGear.includes(drop.id))st.lootGear.push(drop.id);if(!st.equipped[drop.slot])st.equipped[drop.slot]=drop.id}store();toast(`🌟 擊倒稀有怪 ${m[1]}！`);$('statusText').textContent=`稀有怪勝利！獲得 ${coin} 金幣、${xp} XP${drop?`，掉落 ${drop.rarity}「${drop.n}」`:''}！`;$('actions').innerHTML='<button class="btn gold" onclick="returnAfterRare()">帶著戰利品繼續 ➡️</button>';checkLevel();renderHud();renderInventory();renderQuests()}
function returnAfterRare(){battle=null;render();if($('statusText'))$('statusText').textContent='🌟 稀有怪事件結束，繼續尋找地下城的主線怪獸。'}
function continueAdventure(){const w=worlds[st.world-1];battle=null;const all=w.m.every((m,i)=>defeated(w.id).includes(i));if(all){clearWorld(w.id);return}renderScreen();triggerDungeonEvent()}
function returnToEnemySelect(){battle=null;render();}
function checkLevel(){let leveled=false,lastGear=null;while(st.xp>=xpNeed()){st.xp-=xpNeed();st.level++;leveled=true;const g=gear.find(x=>x.lv===st.level&&!st.gear.includes(x.n));if(g){st.gear.push(g.n);lastGear=g}}store();if(leveled){$('levelText').textContent=`升到 Lv.${st.level}！目前 ATK ${attack()}、HP ${hpMax()}、MP ${mpMax()}、DEF ${defense()}${lastGear?'，獲得 '+lastGear.n:''}`;$('levelModal').classList.add('show')}}
function closeLevel(){$('levelModal').classList.remove('show');render()}
function clearWorld(id){if(!st.cleared.includes(id)){st.cleared.push(id);st.stars+=20;st.coins+=10;store();toast(`🏆 Dungeon ${id} 五怪全攻略！`)}render();if(id<7){$('statusText').textContent='五隻怪獸全部擊倒！獲得 20 星＋10 金幣，下一個地下城已解鎖！';$('actions').innerHTML='<button class="btn gold" onclick="nextWorld()">前往下一區 ➡️</button>'}}
function nextWorld(){if(st.world<7)openWorld(st.world+1)}
function statText(g){return [g.atk?`ATK +${g.atk}`:'',g.hp?`HP +${g.hp}`:'',g.mp?`MP +${g.mp}`:'',g.def?`DEF +${g.def}`:''].filter(Boolean).join(' / ')}
function renderInventory(){const slots=['weapon','armor','charm'];const slotNames={weapon:'武器',armor:'防具',charm:'飾品'};const equipped=slots.map(slot=>{const g=lootCatalog.find(x=>x.id===st.equipped[slot]);return `<div class="equipSlot ${g?rarityClass(g.rarity):''}"><small>${slotNames[slot]}</small><div class="i">${g?g.e:'➕'}</div><b>${g?g.n:'尚未裝備'}</b><div>${g?`${g.rarity}｜${statText(g)}`:'商店或寶箱可獲得'}</div></div>`}).join('');const owned=st.lootGear.length?st.lootGear.map(id=>{const g=lootCatalog.find(x=>x.id===id);if(!g)return'';const on=st.equipped[g.slot]===id;return `<button class="ownedItem ${rarityClass(g.rarity)} ${on?'equipped':''}" onclick="equipLoot('${id}')"><span>${g.e}</span><b>${g.n}</b><small>${g.rarity}｜${statText(g)}</small><em>${on?'✅ 裝備中':'點擊裝備'}</em></button>`}).join(''):'<p class="sub">還沒有掉落裝備，去探索寶箱或找神秘商人吧！</p>';$('inventory').innerHTML=`<div class="equipmentSlots">${equipped}</div><div class="bagRow"><b>🎒 道具袋：</b><span>🍎 生命藥水 ×${st.items.potion}</span><span>🔷 法力藥水 ×${st.items.ether}</span><span>🔑 鑰匙 ×${st.items.key}</span></div><h3>✨ 已獲得裝備</h3><div class="ownedGear">${owned}</div><h3>🏅 等級獎勵</h3><div class="levelGear">${gear.map(g=>`<div class="item ${st.gear.includes(g.n)?'':'locked'}"><div class="i">${g.e}</div><b>${g.n}</b><small>Lv.${g.lv}</small></div>`).join('')}</div>`}
function renderQuests(){const q=[['🧠','答對 10 題',st.quest.correct>=10],['⚔️','擊倒 10 怪',st.quest.wins>=10],['🐲','擊倒 2 Boss',st.quest.boss>=2],['🔥','Combo 5',st.quest.combo5>=1]];$('quests').innerHTML=q.map(x=>`<div class="quest ${x[2]?'done':''}"><div class="i">${x[0]}</div><b>${x[1]}</b><div>${x[2]?'✅':'⭐'}</div></div>`).join('')}
function animate(id,c){const el=$(id);if(!el)return;el.classList.add(c);setTimeout(()=>el.classList.remove(c),420)}
function toast(t){$('toast').textContent=t;$('toast').classList.add('visible');setTimeout(()=>$('toast').classList.remove('visible'),1500)}
function resetGame(){if(confirm('確定要清除 V4.5 的全部進度嗎？')){localStorage.removeItem('hero9_v41');location.reload()}}
store();render();