function answerQuestion(btn,i){document.querySelectorAll('.ans').forEach(x=>x.disabled=true);if(i===currentQ.a){btn.classList.add('good');st.stars++;st.combo++;st.quest.correct++;if(st.combo>=5)st.quest.combo5=1;store();setTimeout(()=>{$('qModal').classList.remove('show');resolveSkill(true)},450)}else{btn.classList.add('bad');st.combo=0;store();setTimeout(()=>{$('qModal').classList.remove('show');resolveSkill(false)},600)}}
function resolveSkill(ok){if(!ok){enemyAttack();return}const cost={slash:0,fire:2,heavy:3,heal:3}[battle.skill];battle.mp-=cost;if(battle.skill==='heal'){battle.hp=Math.min(hpMax(),battle.hp+5);animate('heroChar','magic');updateBattle();toast('HP +5');return}const bonus=1+Math.min(st.combo,5)*.12,base=attack()+({slash:0,fire:2,heavy:4}[battle.skill]||0),dmg=Math.round(base*bonus);animate('heroChar',battle.skill==='slash'?'attack':'magic');setTimeout(()=>{animate('monsterChar','hit');battle.mhp=Math.max(0,battle.mhp-dmg);updateBattle();if(battle.mhp<=0)winBattle();else $('statusText').textContent=`命中！造成 ${dmg} 傷害，Combo ${st.combo}`},170)}
function enemyAttack(){animate('monsterChar','enemyAttack');setTimeout(()=>{animate('heroChar','hit');const m=worlds[battle.world-1].m[battle.index],dmg=m[3]?3:2;battle.hp=Math.max(0,battle.hp-dmg);battle.mp=Math.min(mpMax(),battle.mp+1);if(battle.hp===0){battle.hp=hpMax();battle.mp=mpMax();toast('勇者在檢查點復活！')}updateBattle();$('statusText').textContent=`答錯，受到 ${dmg} 傷害；MP +1。`},170)}
function updateBattle(){const m=worlds[battle.world-1].m[battle.index];$('heroHpText').textContent=`${battle.hp}/${hpMax()}`;$('heroHpBar').style.width=battle.hp/hpMax()*100+'%';$('heroMpText').textContent=`${battle.mp}/${mpMax()}`;$('heroMpBar').style.width=battle.mp/mpMax()*100+'%';$('monsterName').textContent=`${m[0]} ${m[1]}`;$('monsterHpText').textContent=`${battle.mhp}/${m[2]}`;$('monsterHpBar').style.width=battle.mhp/m[2]*100+'%';$('monsterChar').textContent=m[0];$('monsterChar').classList.toggle('boss',!!m[3]);renderHud()}
function winBattle(){battle.active=false;const w=worlds[battle.world-1],m=w.m[battle.index];st.defeated[w.id]=st.defeated[w.id]||[];if(!st.defeated[w.id].includes(battle.index))st.defeated[w.id].push(battle.index);const boss=!!m[3];st.coins+=boss?8:3;st.xp+=boss?6:3;st.quest.wins++;if(boss)st.quest.boss++;store();toast(`擊倒 ${m[1]}！`);$('statusText').textContent=`勝利！獲得 ${boss?8:3} 金幣、${boss?6:3} XP。`;$('actions').innerHTML='<button class="btn green" onclick="returnToEnemySelect()">回到敵人選擇 ➡️</button>';checkLevel();renderHud();renderInventory();renderQuests()}
function returnToEnemySelect(){const w=worlds[st.world-1];battle=null;const all=w.m.every((m,i)=>defeated(w.id).includes(i));if(all){clearWorld(w.id);return}renderScreen()}
function checkLevel(){if(st.xp>=xpNeed()){st.xp-=xpNeed();st.level++;const g=gear.find(x=>x.lv===st.level&&!st.gear.includes(x.n));if(g)st.gear.push(g.n);store();$('levelText').textContent=`升到 Lv.${st.level}！攻擊 ${attack()}、HP ${hpMax()}、MP ${mpMax()}${g?'，解鎖 '+g.n:''}`;$('levelModal').classList.add('show')}}
function closeLevel(){$('levelModal').classList.remove('show');render()}
function clearWorld(id){if(!st.cleared.includes(id)){st.cleared.push(id);st.stars+=10;store();toast(`Dungeon ${id} 攻略完成！`)}render();if(id<7){$('statusText').textContent='下一個地下城已解鎖！';$('actions').innerHTML='<button class="btn gold" onclick="nextWorld()">前往下一區 ➡️</button>'}}
function nextWorld(){if(st.world<7)openWorld(st.world+1)}
function renderInventory(){$('inventory').innerHTML=gear.map(g=>`<div class="item ${st.gear.includes(g.n)?'':'locked'}"><div class="i">${g.e}</div><b>${g.n}</b></div>`).join('')}
function renderQuests(){const q=[['🧠','答對 10 題',st.quest.correct>=10],['⚔️','擊倒 5 怪',st.quest.wins>=5],['🐲','擊倒 2 Boss',st.quest.boss>=2],['🔥','Combo 5',st.quest.combo5>=1]];$('quests').innerHTML=q.map(x=>`<div class="quest ${x[2]?'done':''}"><div class="i">${x[0]}</div><b>${x[1]}</b><div>${x[2]?'✅':'⭐'}</div></div>`).join('')}
function animate(id,c){const el=$(id);if(!el)return;el.classList.add(c);setTimeout(()=>el.classList.remove(c),420)}
function toast(t){$('toast').textContent=t;$('toast').classList.add('visible');setTimeout(()=>$('toast').classList.remove('visible'),1000)}
function resetGame(){if(confirm('確定要清除 V4.3 的全部進度嗎？')){localStorage.removeItem('hero9_v41');location.reload()}}
render();