const consumableCatalog=[
{id:'potion',kind:'item',e:'🍎',n:'生命藥水',price:7,desc:'戰鬥中回復 5 HP'},
{id:'ether',kind:'item',e:'🔷',n:'法力藥水',price:8,desc:'戰鬥中回復 4 MP'},
{id:'key',kind:'item',e:'🔑',n:'寶箱鑰匙',price:12,desc:'開啟高級寶箱'}
];
let currentShop=[];
function rarityClass(r){return {'普通':'common','稀有':'rare','史詩':'epic','傳說':'legendary'}[r]||'common'}
function weightedRarity(){const n=Math.random()*100;return n<45?'普通':n<75?'稀有':n<93?'史詩':'傳說'}
function randomGear(){for(let i=0;i<20;i++){const r=weightedRarity(),pool=lootCatalog.filter(x=>x.rarity===r);if(pool.length)return pool[Math.floor(Math.random()*pool.length)]}return lootCatalog[0]}
function makeShopStock(){const result=[];while(result.length<2){const g=randomGear();if(!result.some(x=>x.id===g.id))result.push({...g,kind:'gear'})}const c=consumableCatalog[Math.floor(Math.random()*consumableCatalog.length)];result.push(c);return result.sort(()=>Math.random()-.5)}
function openEventModal(title,icon,html,actions=''){const modal=$('eventModal');$('eventIcon').textContent=icon;$('eventTitle').textContent=title;$('eventBody').innerHTML=html;$('eventActions').innerHTML=actions;modal.classList.add('show')}
function closeEventModal(){if($('eventModal'))$('eventModal').classList.remove('show')}
function continueAfterEvent(){closeEventModal();battle=null;render();const w=worlds[st.world-1],left=w.m.length-defeated(w.id).length;if($('statusText'))$('statusText').textContent=`🧭 事件結束，繼續探索！本區還有 ${left} 隻怪獸。`}
function triggerDungeonEvent(){st.events++;store();const r=Math.random();if(r<.24)return eventShop();if(r<.46)return eventChest();if(r<.63)return eventFountain();if(r<.76)return eventTrap();if(r<.89)return eventFork();return eventRareMonster()}
function eventShop(){currentShop=makeShopStock();renderShop()}
function renderShop(){const cards=currentShop.map((x,i)=>{if(x.kind==='gear'){const owned=st.lootGear.includes(x.id);return `<div class="shopItem ${rarityClass(x.rarity)}"><div class="shopEmoji">${x.e}</div><div class="rarity">${x.rarity}</div><b>${x.n}</b><small>${x.slot==='weapon'?'武器':x.slot==='armor'?'防具':'飾品'}｜${x.atk?`ATK +${x.atk} `:''}${x.hp?`HP +${x.hp} `:''}${x.mp?`MP +${x.mp} `:''}${x.def?`DEF +${x.def}`:''}</small><div class="price">🪙 ${x.price}</div><button class="btn ${owned?'soft':'gold'}" ${owned?'disabled':''} onclick="buyShopItem(${i})">${owned?'已擁有':'購買'}</button></div>`}return `<div class="shopItem common"><div class="shopEmoji">${x.e}</div><div class="rarity">消耗品</div><b>${x.n}</b><small>${x.desc}</small><div class="price">🪙 ${x.price}</div><button class="btn gold" onclick="buyShopItem(${i})">購買</button></div>`}).join('');openEventModal('神秘商人','🧙',`<p>商人的斗篷一掀開——這次只賣這三件！下次遇見商品會重新刷新。</p><div class="shopCoins">你的金幣：🪙 <b>${st.coins}</b></div><div class="shopGrid">${cards}</div>`,`<button class="btn soft" onclick="continueAfterEvent()">離開商店 ➡️</button>`)}
function buyShopItem(i){const x=currentShop[i];if(!x)return;if(st.coins<x.price){toast('🪙 金幣不夠！');return}st.coins-=x.price;if(x.kind==='gear'){if(!st.lootGear.includes(x.id))st.lootGear.push(x.id);if(!st.equipped[x.slot])st.equipped[x.slot]=x.id;toast(`${x.e} 買到 ${x.n}！`)}else{st.items[x.id]=(st.items[x.id]||0)+1;toast(`${x.e} ${x.n} +1`)}store();renderHud();renderShop();renderInventory()}
function eventChest(){const gold=5+Math.floor(Math.random()*8);const hasKey=st.items.key>0;const actions=`<button class="btn gold" onclick="openNormalChest(${gold})">直接打開</button>${hasKey?'<button class="btn purple" onclick="openKeyChest()">🔑 用鑰匙開高級寶箱</button>':''}<button class="btn soft" onclick="continueAfterEvent()">先不開</button>`;openEventModal('發現寶箱','🎁',`<p>石牆後面藏著一個閃亮寶箱！普通開啟至少有金幣；使用鑰匙有更高機率得到稀有裝備。</p><p>目前鑰匙：🔑 ${st.items.key}</p>`,actions)}
function openNormalChest(gold){st.coins+=gold;let extra='';if(Math.random()<.28){const id=Math.random()<.55?'potion':'ether';st.items[id]++;extra=`，另外找到 ${id==='potion'?'🍎生命藥水':'🔷法力藥水'} ×1`}store();openEventModal('寶箱打開了！','✨',`<p>獲得 🪙 <b>${gold}</b> 金幣${extra}！</p>`,`<button class="btn green" onclick="continueAfterEvent()">收下並繼續 ➡️</button>`);renderHud()}
function openKeyChest(){if(st.items.key<=0)return;st.items.key--;let g=randomGear();if(g.rarity==='普通'){const rarePool=lootCatalog.filter(x=>x.rarity==='稀有');g=rarePool[Math.floor(Math.random()*rarePool.length)]}if(!st.lootGear.includes(g.id))st.lootGear.push(g.id);if(!st.equipped[g.slot])st.equipped[g.slot]=g.id;store();openEventModal('高級寶箱！','🌟',`<p>鑰匙發出金光！你獲得：</p><div class="lootReveal ${rarityClass(g.rarity)}"><div>${g.e}</div><b>${g.rarity}｜${g.n}</b></div>`,`<button class="btn green" onclick="continueAfterEvent()">收下裝備 ➡️</button>`);renderHud();renderInventory()}
function eventFountain(){openEventModal('神秘泉水','⛲',`<p>清澈泉水散發魔力。你可以選擇帶走一瓶生命藥水，或凝聚成法力藥水。</p>`,`<button class="btn green" onclick="takeFountain('potion')">🍎 生命藥水</button><button class="btn blue" onclick="takeFountain('ether')">🔷 法力藥水</button>`)}
function takeFountain(type){st.items[type]++;store();toast(`${type==='potion'?'🍎 生命藥水':'🔷 法力藥水'} +1`);continueAfterEvent();renderHud()}
function eventTrap(){openEventModal('陷阱房間','💀',`<p>前方地板有奇怪的符號。要小心拆除，還是快速跳過？</p>`,`<button class="btn purple" onclick="resolveTrap('disarm')">🧠 小心拆除</button><button class="btn gold" onclick="resolveTrap('jump')">🏃 快速跳過</button>`)}
function resolveTrap(choice){const chance=choice==='disarm'?.72:.52;if(Math.random()<chance){const gain=4+Math.floor(Math.random()*5);st.coins+=gain;store();openEventModal('成功通過！','✅',`<p>你破解了機關，還在暗格找到 🪙 ${gain} 金幣。</p>`,`<button class="btn green" onclick="continueAfterEvent()">繼續 ➡️</button>`)}else{const loss=Math.min(st.coins,3+Math.floor(Math.random()*4));st.coins-=loss;store();openEventModal('踩到陷阱！','💥',`<p>機關啟動！慌亂中掉了 🪙 ${loss} 金幣。下次再判斷仔細一點。</p>`,`<button class="btn soft" onclick="continueAfterEvent()">繼續 ➡️</button>`)}renderHud()}
function eventFork(){const left=['🌲 森林小徑','🕯️ 黑暗通道','🌉 古老石橋'][Math.floor(Math.random()*3)],right=['💎 閃光洞穴','🌀 魔法門','🏚️ 廢棄營地'][Math.floor(Math.random()*3)];openEventModal('地下城岔路','🧭',`<p>兩條路都看不到盡頭。選一條探索，獎勵和風險都不一樣。</p>`,`<button class="btn green" onclick="resolveFork()">⬅️ ${left}</button><button class="btn purple" onclick="resolveFork()">${right} ➡️</button>`)}
function resolveFork(){const r=Math.random();if(r<.45){const gain=6+Math.floor(Math.random()*7);st.coins+=gain;store();openEventModal('找到秘密藏寶處！','💰',`<p>路的盡頭藏著 🪙 ${gain} 金幣！</p>`,`<button class="btn green" onclick="continueAfterEvent()">繼續 ➡️</button>`)}else if(r<.75){const item=Math.random()<.5?'potion':'ether';st.items[item]++;store();openEventModal('發現冒險者補給！','🎒',`<p>得到 ${item==='potion'?'🍎 生命藥水':'🔷 法力藥水'} ×1。</p>`,`<button class="btn green" onclick="continueAfterEvent()">繼續 ➡️</button>`)}else{openEventModal('繞了一圈...','🌀',`<p>這條路竟然是死路！沒有損失，但什麼也沒找到。</p>`,`<button class="btn soft" onclick="continueAfterEvent()">返回主路 ➡️</button>`)}renderHud()}
function eventRareMonster(){const rares=[['🦄','幻光寶獸'],['🦅','黃金獅鷲'],['🐲','幼年星龍'],['🦊','九尾靈狐'],['👾','異界史萊姆']];const r=rares[Math.floor(Math.random()*rares.length)],hp=10+st.world*3;openEventModal('稀有怪出現！','🌟',`<p><span style="font-size:64px">${r[0]}</span></p><p><b>${r[1]}</b> 從隱藏區域現身！擊敗牠會得到大量金幣與高級掉寶。</p>`,`<button class="btn red" onclick="startRareBattle('${r[0]}','${r[1]}',${hp})">⚔️ 挑戰稀有怪</button><button class="btn soft" onclick="continueAfterEvent()">安全離開</button>`)}
function startRareBattle(e,n,hp){closeEventModal();battle={world:st.world,index:-1,hp:hpMax(),mp:mpMax(),mhp:hp,skill:'slash',active:true,enemyWeaken:0,rare:true,monster:[e,n,hp]};updateBattle();$('statusText').textContent=`🌟 稀有怪 ${n} 出現！牠身上散發著寶物的光芒！`;$('actions').innerHTML=skillButtons();toast(`🌟 ${n} 亂入！`)}