function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function rand(a,b){return Math.floor(Math.random()*(b-a+1))+a}
function makeMC(p,correct,wrongs,cat,key){let opts=shuffle([String(correct),...wrongs.map(String)].filter((v,i,a)=>a.indexOf(v)===i));while(opts.length<4){let x=String(rand(1,99));if(!opts.includes(x))opts.push(x)}opts=shuffle(opts.slice(0,4));return {p,o:opts,a:opts.indexOf(String(correct)),cat,key:key||p}}
function remember(q){st.history=st.history||[];st.history.push(q.key||q.p);if(st.history.length>12)st.history=st.history.slice(-12);store();return q}
function uniqueQuestion(factory){st.history=st.history||[];let q;for(let i=0;i<20;i++){q=factory();if(!st.history.includes(q.key||q.p))return remember(q)}return remember(q)}
function mathMultiply(){let a=rand(3,12),b=rand(3,12),c=a*b;return makeMC(`${a} × ${b} = ?`,c,[c+a,c-b,c+rand(2,9)],'乘法',`mul:${a}:${b}`)}
function mathDivision(){let b=rand(3,12),q=rand(3,12),a=b*q;return makeMC(`${a} ÷ ${b} = ?`,q,[q+1,Math.max(1,q-1),q+2],'除法',`div:${a}:${b}`)}
function moneyProblem(){let price=rand(12,68),pay=[50,80,100,120][rand(0,3)];if(pay<=price)pay=price+rand(15,40);let ans=pay-price;return makeMC(`你有 ${pay} 元，買一件 ${price} 元的裝備，會剩多少元？`,ans,[ans+5,Math.max(0,ans-5),ans+10],'應用題',`money:${pay}:${price}`)}
function twoStepProblem(){let boxes=rand(3,8),each=rand(4,9),give=rand(2,8),total=boxes*each-give;return makeMC(`${boxes} 箱藥水，每箱 ${each} 瓶，送給隊友 ${give} 瓶後，還剩幾瓶？`,total,[total+give,total-each,total+each],'兩步驟',`two:${boxes}:${each}:${give}`)}
function fractionCompare(){let den=[4,5,6,8,10][rand(0,4)],a=rand(1,den-1),b=rand(1,den-1);while(a===b)b=rand(1,den-1);let ca=`${a}/${den}`,cb=`${b}/${den}`,correct=a>b?ca:cb;return {p:`哪一個比較大？ <b>${ca}</b> 或 <b>${cb}</b>`,o:shuffle([ca,cb,'一樣大','無法比較']),a:0,cat:'分數',key:`frac:${a}:${b}:${den}`,_correct:correct}}
function normalizeFraction(q){q.a=q.o.indexOf(q._correct);delete q._correct;return q}
function decimalCompare(){let a=(rand(10,95)/100).toFixed(2),b=(rand(10,95)/100).toFixed(2);while(a===b)b=(rand(10,95)/100).toFixed(2);let correct=Number(a)>Number(b)?a:b;let opts=shuffle([a,b,'一樣大','無法比較']);return {p:`哪一個數比較大？ <b>${a}</b> 或 <b>${b}</b>`,o:opts,a:opts.indexOf(correct),cat:'小數',key:`dec:${a}:${b}`}}
function patternQuestion(){let start=rand(1,12),step=rand(2,9),seq=[0,1,2,3].map(i=>start+i*step),ans=start+4*step;return makeMC(`數列：${seq.join('、')}、？`,ans,[ans-step,ans+step,ans+2],'數列',`pat:${start}:${step}`)}
function doublePattern(){let start=rand(1,5),seq=[start,start*2,start*4,start*8],ans=start*16;return makeMC(`找規律：${seq.join('、')}、？`,ans,[ans/2,ans+start,ans*2],'規律',`dbl:${start}`)}
function perimeterQuestion(){let l=rand(3,12),w=rand(2,9),ans=2*(l+w);return makeMC(`長方形長 ${l} cm、寬 ${w} cm，周長是多少 cm？`,ans,[l*w,l+w,ans+2],'幾何',`peri:${l}:${w}`)}
function timeQuestion(){let h=rand(1,3),m=[15,20,30,45][rand(0,3)],ans=h*60+m;return makeMC(`${h} 小時 ${m} 分鐘一共是多少分鐘？`,ans,[h*60,m,ans-10],'時間',`time:${h}:${m}`)}
function directionQuestion(){const qs=[['你面向北方，向右轉後面向哪裡？','東方',['西方','南方','北方']],['你面向東方，向左轉後面向哪裡？','北方',['南方','西方','東方']],['你面向南方，轉身 180° 後面向哪裡？','北方',['東方','西方','南方']],['從起點往東走 3 格，再往北走 2 格，最後在起點的哪個方向？','東北方',['西北方','東南方','西南方']]];let q=qs[rand(0,qs.length-1)];return makeMC(q[0],q[1],q[2],'方向邏輯',`dir:${q[0]}`)}
const englishPool=[['Which word means「勇敢」?','brave',['quiet','weak','tiny']],['Opposite of “early”?','late',['fast','near','short']],['Past tense of “go”?','went',['goed','gone','going']],['Past tense of “eat”?','ate',['eated','eaten','eating']],['Past tense of “see”?','saw',['seed','seen','seeing']],['Which word means「安靜的」?','quiet',['loud','bright','fast']],['Choose the correct sentence.','She has a book.',['She have a book.','She having a book.','She are a book.']],['Choose the correct sentence.','They are ready.',['They is ready.','They am ready.','They be ready.']],['Choose the correct sentence.','He goes to school.',['He go to school.','He going to school.','He gone school.']],['Which word means「危險的」?','dangerous',['delicious','careful','simple']],['Which spelling is correct?','because',['becaus','becouse','beacause']],['Which spelling is correct?','friend',['freind','frend','friand']],['What is the plural of “child”?','children',['childs','childes','childrens']],['What is the plural of “mouse”?','mice',['mouses','mousees','mices']],['Which word is a verb?','run',['blue','happy','table']],['Which word is an adjective?','strong',['jump','book','slowly']],['Complete: I ___ a student.','am',['is','are','be']],['Complete: We ___ friends.','are',['is','am','be']],['Which means「昨天」?','yesterday',['tomorrow','today','tonight']],['Which means「明天」?','tomorrow',['yesterday','before','last']]];
function englishQuestion(){let q=englishPool[rand(0,englishPool.length-1)];return makeMC(q[0],q[1],q[2],'英文',`eng:${q[0]}`)}
const sciencePool=[['水在標準大氣壓下加熱到約 100°C 通常會？','沸騰',['結冰','凝固','變成石頭']],['植物製造養分主要利用哪種能量？','陽光',['聲音','磁力','摩擦']],['哪一個是哺乳類？','海豚',['鯊魚','章魚','企鵝']],['影子的方向通常和光源方向？','相反',['相同','永遠向北','完全無關']],['冰塊融化是什麼狀態變化？','固態→液態',['液態→氣態','氣態→固態','液態→固態']],['水蒸氣遇冷形成小水滴叫做？','凝結',['蒸發','融化','燃燒']],['下列哪一個是導體？','銅線',['橡皮擦','塑膠尺','木筷']],['磁鐵最容易吸引哪一種物品？','鐵釘',['玻璃珠','塑膠片','橡皮筋']],['地球繞著哪個天體公轉？','太陽',['月球','火星','北極星']],['月球本身會發光嗎？','不會，它反射太陽光',['會，自己發光','只有白天會','只有滿月會']],['植物的根主要功能之一是？','吸收水分',['製造聲音','發出月光','產生磁力']],['食物鏈中，植物通常屬於？','生產者',['消費者','分解者','掠食者']],['聲音需要什麼才能傳播？','介質',['真空一定最好','只有光','只有磁場']],['哪種力會讓物體落向地面？','重力',['浮力','磁力','彈力']],['白天與黑夜主要是因為？','地球自轉',['地球公轉','月球自轉','太陽繞地球']],['一年四季主要與什麼有關？','地球公轉與地軸傾斜',['月球大小','海水顏色','風向固定']]];
function scienceQuestion(){let q=sciencePool[rand(0,sciencePool.length-1)];return makeMC(q[0],q[1],q[2],'科學',`sci:${q[0]}`)}
function logicQuestion(){const qs=[['所有紅色鑰匙都能開紅門。這把是紅色鑰匙，最合理的是？','它能開紅門',['它一定能飛','它不能開紅門','它會變色']],['A 比 B 高，B 比 C 高，誰最高？','A',['B','C','一樣高']],['小明比小華早到，小華比小美早到，誰最後到？','小美',['小明','小華','無法知道']],['若今天星期三，3 天後是星期幾？','星期六',['星期五','星期日','星期一']],['盒子裡只有紅球與藍球。拿到的不是紅球，那一定是？','藍球',['綠球','黃球','白球']]];let q=qs[rand(0,qs.length-1)];return makeMC(q[0],q[1],q[2],'邏輯',`logic:${q[0]}`)}
function getQuestion(w){return uniqueQuestion(()=>{let r=Math.random();if(w===1)return r<.45?mathMultiply():r<.7?moneyProblem():englishQuestion();if(w===2)return r<.35?mathDivision():r<.65?twoStepProblem():r<.82?timeQuestion():moneyProblem();if(w===3)return r<.32?normalizeFraction(fractionCompare()):r<.58?decimalCompare():r<.8?perimeterQuestion():mathDivision();if(w===4)return r<.32?patternQuestion():r<.55?doublePattern():r<.78?directionQuestion():logicQuestion();if(w===5)return englishQuestion();if(w===6)return r<.7?scienceQuestion():logicQuestion();let pick=rand(1,6);return getBossMixed(pick)})}
function getBossMixed(pick){if(pick===1)return Math.random()<.5?mathMultiply():moneyProblem();if(pick===2)return Math.random()<.5?mathDivision():twoStepProblem();if(pick===3)return Math.random()<.5?normalizeFraction(fractionCompare()):decimalCompare();if(pick===4)return Math.random()<.5?patternQuestion():logicQuestion();if(pick===5)return englishQuestion();return scienceQuestion()}